openapi: 3.0.0
info:
  title: Toko Baju Online
  version: 1.0.0
servers:
  - url: http://localhost:8080
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /login:
    post:
      tags:
        - default
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: Banban
                password: '12345'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /regis:
    post:
      tags:
        - default
      summary: Regis
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: danymr@gmail.com
                username: Budiono
                password: '12345'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /pakaian:
    get:
      tags:
        - default
      summary: Get All pakaian
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: Post Pakaian
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                namapakaian: Baju Berbulu
                deskripsi: Bagus untuk musim dingin
                ukuran: XL
                stok: 25
                hargapakaian: 500000
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /pakaian/3:
    put:
      tags:
        - default
      summary: Update Pakaian
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                namapakaian: Baju Berbulu Rusa
                deskripsi: Bagus untuk musim yang sangat dingin
                ukuran: XXL
                stok: 254
                hargapakaian: 50100
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /pakaian/5:
    delete:
      tags:
        - default
      summary: Delete Pakaian
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /pembeli:
    get:
      tags:
        - default
      summary: Get Pembeli
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: Post Pembeli
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                nama: Jane Doe
                email: jane.doe@example.com
                jumlahpembelian: 50
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /pembeli/4:
    put:
      tags:
        - default
      summary: Update Pembeli
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                nama: jodi didodo
                email: joko.doe@example.com
                jumlahpembelian: 100
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: Delete Pembeli
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
